### ISSUE TITLE
A long silence makes it jump to the end of the file

### ISSUE THREAD

**Issue by BruceFraser1** [flackbash/AudioAnchor#138]
When AudioAnchor encounters a long silence, such as a new section or chapter (still the same MP3 file), it jumps to the end of the file.
I play the same file, at the same location, in an ordinary media player (VLC), and it plays through that place without stopping.

**Comment by flackbash** [comment]
Do you have an example file that you could send me, e.g. to the email address [here](https://ad.informatik.uni-freiburg.de/staff/prange)?

**Comment by flackbash** [comment]
Thanks for the file and the explanation, Bruce!

AudioAnchor uses the Android [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer) internally. 
Apparently, this player has a problem with the encoding of your audio file. I didn't find much on this issue, but there's something that sounds similar on [Stackoverflow](https://stackoverflow.com/questions/21706478/mediaplayer-issue-plays-mp3s-too-fast-skips-encoded-silence).

I used a sound converter ([this one](https://soundconverter.org/) on Linux, but there will be similar converters for Windows) to convert your file to mp3 again (with a constant bit rate). The resulting file worked without problems in AudioAnchor.

Unfortunately, to solve the issue on AudioAnchor's side, there doesn't seem to be much that I can do other than moving away from Android's `MediaPlayer`, which would be a lot of work and is therefore not planned. Maybe running a simple converter over your files is an option for you? Or maybe there is an option in the [program you use](http://www.makeitone.net/audio/mp3albummaker.htm) in order to create a single audio file from several that allows you to create commonly playable audio files? Note that a constant bit rate (CBR) is always preferable for AudioAnchor.

**Comment by BruceFraser1** [comment]
Thanks for your help.
The problem was with the software I used to join MP3 files: MakeItOne MP3 Album Maker 3.4. It apparently adds or deletes bits at the joints, making the resulting file unreliable.
I tried several other softwares, and the easiest to use, which causes no problem is: Shuangs Audio Joiner 2.5. It's available on many software websites; here's one: https://www.softpedia.com/get/Multimedia/Audio/Audio-Editors-Recorders/Shuangs-Audio-Joiner.shtml.
