### ISSUE TITLE
Progress text in "Now playing" UI is cut-off on smaller displays

### ISSUE THREAD

**Issue by tobykurien** [flackbash/AudioAnchor#139]
The UI seems to get cut-off at the bottom when running on a 4.5" 480x854 display (https://www.gsmarena.com/micromax_canvas_a1-6686.php).

Screenshot:
![photo_2022-01-29_10-21-50](https://user-images.githubusercontent.com/972315/151653825-5dbb1349-ab04-4ec6-8fd1-9867753cf7c1.jpg)

Edit: Also just wanted to say that I love the app, it was really hard to find an app that works this way (adding folders and remembering where each left off), so thank you and great job!

**Comment by flackbash** [comment]
Thanks for reporting this! I'll have a look at it.

**Comment by flackbash** [comment]
I pushed a fix for this which will be in the next release.
I ran it on an emulator and it looked fine to me.
Still, if you have the possibility, it would be great if you could test it before and let me know if it works for you :)
Otherwise I'll publish a new release probably at some point next week.
