### ISSUE TITLE
Bluetooth play back issue

### ISSUE THREAD

**Issue by troypulk** [flackbash/AudioAnchor#151]
This issue started with 2.3, Bluetooth causes AudioAnchor to only play 3 files at a time.

Tested by turning off Bluetooth and rebooting AudioAnchor then continued playing files, the files played more than 3. Autoplay is enabled.

AudioAnchor Version 2.3.0
Oneplus 5t, Android 11, LinageOS, No google services installed, downloaded from fdroid 
18.1-20220322-NIGHTLY-dumpling

**Comment by flackbash** [comment]
Thanks for reporting this. I could not reproduce the error yet (but I'm not on Android 11).

Do I understand you correctly, the steps to reproduce this are:
- pair Bluetooth device with phone,
- start AudioAnchor playback with autoplay enabled,
--> AudioAnchor stops playback after having played the third track.

Does it matter whether the tracks are short (e.g. 2,3 minutes) or longer?

What happens if you set one skip button to "next track" and then skip to the next track during playback? Does it still stop after the 3rd track or after the 4th?

**Comment by troypulk** [comment]
As it turns out, I uninstalled the 2.3 version because it was unusable and reinstalled 2.2.6. I reinstalled 2.3 today and tested it again and I cannot reproduce the error.
So it looks like some anomaly of some kind, I'm not sure.

So you can delete this thread.

Good day to you

**Comment by flackbash** [comment]
Weird.. feel free to reopen this should you encounter the bug again.
