### ISSUE TITLE
Can't play tracks already listened to

### ISSUE THREAD

**Issue by johnstonesnow** [flackbash/AudioAnchor#168]
I have played with all settings, struggle to understand the explanations on some, but still tried all options. 

In audiobooks, if I want to skip back and listen to a chapter I have listened to previously, it just jumps to my last played position. Since I can't stop it doing it I am assuming it's a bug?

PS I just noticed permissions:

"Read phone status and identity:
Allows the app to access the phone features of the device. This permission allows the app to determine the phone number and device IDs, whether a call is active, and the remote number connected by a call."

Does anyone know why the app wants this permission?

**Comment by flackbash** [comment]
Is this what you are doing: Within AudioAnchor you open the player (PlayActivity) for a track where your last playback position is at the very end. You now seek to the beginning of the track (or some position other than the very end) using the search bar or the skip interval buttons (-10, -30). You press play and the result is that the position in the seekbar jumps back to the end of that track?
That would indeed be a bug. In that case, please send me some more information, e.g. Android version, AudioAnchor version, whether you are listening via bluetooth and maybe even the file for which this is happening (if that is possible I can give you an email address so you don't have to publicly send it).

Note: When you press play, AudioAnchor always (with default settings) starts at the last playback position. So if you press play on a completed file, it will not start from the beginning, but simply do nothing or skip to the next file if autoplay is enabled.

The phone status permission is only needed to handle audio during an active call, i.e. stopping playback during the call and resuming afterwards. So AudioAnchor does not retrieve the phone number, device ID or remote number but simply checks whether a call is active. You can check the [MediaPlayerService](https://github.com/flackbash/AudioAnchor/blob/master/app/src/main/java/com/prangesoftwaresolutions/audioanchor/services/MediaPlayerService.java) for details.

**Comment by johnstonesnow** [comment]
Hi, thanks for that. 

Firstly, I can't read code. But I will take your word for it that it's not sending you my phone conversation data, I can't have anyone knowing about my plans for world domination :)

As to the 'bug', I am a bit confused but I think what I am describing is 'default behaviour'! I need to find a way around it though. I am listening to 3 different audiobooks at the moment, and i sometimes want to go back and listen to a past chapter i have already listened to. The way I use the app is:

I tap on the app icon from home screen. I have maybe 10 audiobooks in the app so I tap on the one i want, scroll to the chapter i want to listen to and tap there. So let's say I tap on Chapter 17, IF I have already listened to it and already listened to 18 and 19 to, it will jump to chapter 20 and start playing that chapter instead. I can see why some find that convenient, most probably, but it basically is a BAN on me ever listening to past tracks again :D. Since I do this a fair bit, if there's a workaround I'd be grateful to know how. 

Another thing which I notice it does all the time, and this is very annoying so may be a bug or I just don't understand the settings properly, it auto starts from the beginning of the track. So for example, right now. I have just been out in the car and listened to a few minutes while I was driving (just on phone, not bluetooth). I was about 14 minutes into the chapter when I paused it (when i got out of the car). When I read this message from you, I have just opened the app again and it lands me on the same chapter but starts playing from the beginning, not where i was when I hit pause an hour ago. 

Any help very much appreciated. It's my go to app for audiobooks and it's superb, if only I could listen to past tracks! Hell, I would go without ANY saved state data, and just do as I used to with whatever app i used to use.... I'd just take a screenshot when I tapped pause :0D

**Comment by flackbash** [comment]
Hmm ok. So the last thing you mentioned is definitely not default behavior, the progress should be saved every time you hit pause (and on some other occasions, too) so you should be able to continue at the last position. It's always very difficult to fix a bug I can't reproduce, but still it might help to have some basic information about your setup (first and foremost Android version & AudioAnchor version).

The other thing does indeed sound like default behavior :) From your description I take it you have autoplay enabled in the settings. There exists an option in the settings "Replay tracks from beginning when playing next/previous track". If you enable this, every time AudioAnchor jumps to the next or previous track (either due to autoplay or because you used the next/previous buttons which you can set up in the settings), that track is played from the beginning. Then your work flow could look like this: [Enable said option once], open the player for chapter 17, set the seek bar to the beginning of the track and start playback. Every following track will then be played from the beginning again.
Does this help? :)

I've been meaning to write down some documentation for the different options in the settings, because many of them are not self-explanatory, but there's a lot on my AudioAnchor TODO list and not a lot of time. Plus I'm not sure if people would find the documentation if I put it on Github (even with a link in the About page) and within the app there's not really a good place for it.

**Comment by johnstonesnow** [comment]
So kind of you to reply and in so much detail, thank you. 

Ok, the last thing I mentioned, jumping back to start from middle.... if you drop me an email to qw55zz@masqt.com, I can reply with any specifics. Thanks

yes it's tricky to explain what the settings do, especially when they can actually result in several different changes in behaviour, hard to hide tooltips isn't it! I'd say for it re the github page explaining it, if only very briefly. I for one would click through to look, especailly when frustrated with my user experience (most likely due to my own lack of understanding or misuse of the options!)

"I take it you have autoplay enabled in the settings" - I do yes. But I can turn it off. That's one of those I really wasn't sure about as I do'nt know what it does. I assumed (at first) that it means tracks start playing when a track is selected, but then I found another setting which states that it does that, so I am back to not sure again :D

""Replay tracks from beginning when playing next/previous track". If you enable this, every time AudioAnchor jumps to the next or previous track (either due to autoplay or because you used the next/previous buttons which you can set up in the settings), that track is played from the beginning." - Yes, that one makes sense and I don't have a problem with it doing that, but I never really skip to next track. I just let it play through them automatically. The only thing I need is to be able to listen to past tracks (that I have already listened to). The way mine is setup now, I am totally prevented from ever hearing tracks again if I have already played them. The only workaround I can think of is to wipe all saved state data. That's doable, but if there's a better way please let me know. :) 

Thanks again, much appreciated.

**Comment by johnstonesnow** [comment]
PS I just tested the "Autoplay" and I now realise this does just mean automatically play the next track when one ends.

The main two settings I don't understand are the two under "Bookmarks", could you perhaps explain those two, and even what bookmarks are exactly? Thanks :)

**Comment by flackbash** [comment]
"I just tested the "Autoplay" and I now realise this does just mean automatically play the next track when one ends."
Exactly.

"Yes, that one makes sense and I don't have a problem with it doing that, but I never really skip to next track."
The "Replay tracks from beginning when playing next/previous track" has the same effect when the next track is played due to Autoplay. So please try the following setup, I think this is what you want:
* Enable Autoplay (CHECK, you have that already)
* Enable "Replay tracks from beginning when playing next/previous track"
* Now when you go back to an already completed track, seek to the beginning of the track using the progress bar and press play. Now the track will start from the beginning, and all tracks that are played afterwards due to autoplay will also start from the beginning even if you have completed them already.

As an alternative you can also long-click on a track in the track overview, select all tracks where you want to reset the playback position to the beginning and select "Mark as not started" from the menu.

**About bookmarks:**
Bookmarks are there to save certain playback positions of a file. In the player there is a little bookmark icon, when you press that, you can add a bookmark for the current playback position.
You can view the bookmarks for a certain track when you click on the menu in the player and select "Bookmarks". By selecting one of the bookmarks you jump to that position within the track.
Usually when you click the bookmark icon, a dialog opens where you can add a bookmark name and edit the time stamp. 
With the setting "Add bookmark with a single click on the bookmark icon" the bookmark is added without first opening this dialog.
If you enable the other bookmark option with the very long title, every time you press play, a bookmark "<last play position>" and "<second to last play position>" are added or updated and point to the last play position and the second to last play position (as the names suggest). This is a fail safe for when the last stop position was for some reason not stored.

**Comment by johnstonesnow** [comment]
Thanks very much again. 

Yep I have those settings. But ...

"Now when you go back to an already completed track, seek to the beginning of the track using the progress bar and press play. Now the track will start from the beginning, and all tracks that are played afterwards due to autoplay will also start from the beginning even if you have completed them already."

I can't do that. If i scroll up the track list to a previously played track, I tap on it and i never see any bar to drag back to the beginning, it skims to the latest track i have been playing. No way to select anywhere on the play bar. 

I will just "mark as not started" for all previous tracks, that will get me working ok i think. 
Thanks

**Comment by flackbash** [comment]
Aah ok I see, then you need to additionally disable the "Start playback immediately after selecting item".
It was an unfortunate combination of settings for your use case :)

**Comment by johnstonesnow** [comment]
I will try that. Thanks very very much :)
