### ISSUE TITLE
No audio files found in this album

### ISSUE THREAD

**Issue by sezanzeb** [flackbash/AudioAnchor#184]
I have two folders. Both are filled with mp3s.

One of them is detected properly, the other one not.

I have no clue on how to obtain logs or anything from android apps. Or what kind of information android developers need. Please tell me how I can help debug this.
- LineageOS 19.1
- AudioAnchor 2.3.2

**Comment by flackbash** [comment]
Some first thoughts to get a better idea of this:
1) Are they both contained in the same directory and you added the parent directory with the option "Add directory with subdirectories..."?
2) Does the name of the folder that is not detected contain any special characters?

**Comment by sezanzeb** [comment]
I have them on my sd card and I'm **really** confused about how my smartphone handles those on the file system. I'm not even sure if I can navigate to the sd card with audioanchor. I don't know, in the beginning it looked like sd-card content and internal storage are somehow merged together.

I converted the files to flac on the pc and am listening to them now in audioanchor.

**Comment by flackbash** [comment]
I see, then this is most likely just this issue #111, since LineageOS is based on Android 12 it seems. Due to some heavy changes in Android 11, SD storage cannot be selected anymore (unless it's formatted as internal storage).
I will have to fix this eventually as it becomes more and more pressing, but it's an issue that will take a lot of time to work on and I've been successfully putting it off for quite some time now.

**Comment by sezanzeb** [comment]
Allright, thanks. I'll keep an eye open on the issue
