### ISSUE TITLE
Feature request: ability to select directories on external storage

### ISSUE THREAD

**Issue by HansCronau** [flackbash/AudioAnchor#21]

**Comment by jubalh** [comment]
Did you read https://github.com/flackbash/AudioAnchor/issues/2 ?

**Comment by HansCronau** [comment]
No, because it's closed and I'm on the latest version.  

I have found something interesting though: it _is_ possible to navigate to the external storage, it's the _internal_ storage that isn't listed. Sorry for my confusion.

Navigating up from my default /storage/emulated/0 I got confused because under /storage only one folder is listed. I thought it was the internal storage I just navigated out of, but it was the external storage instead. It was the internal storage that was missing.

This would change the issue from a feature request to... a bug? Or is this expected?

**Comment by flackbash** [comment]
As mentioned in #2, I don't have permission to read `/storage/emulated/`. For this it seems, root privileges are required. However, since you are able to navigate to external storage and you start in `/storage/emulated/0 ` per default which is part of the internal storage, you should be able to navigate to any directory. You just can't navigate back to internal storage once you've reached `/storage/emulated/`. In this case you would have to cancel the directory selection and start again in `/storage/emulated/0` or `/storage/emulated/0/Music` (of course not a perfect solution, but it should work).
Let me know if that solves your problem or if there is another issue that I haven't observed yet.

**Comment by HansCronau** [comment]
I see. It seems I don't really have a problem other than this not being clear to me at first. I mostly hoped to provide useful feedback. :)

**Comment by flackbash** [comment]
I have implemented a workaround to be able to display all directories properly. This will be in the next release. Thanks for the feedback!

**Comment by HansCronau** [comment]
Great to hear. :D
