### ISSUE TITLE
App crashes when long press on a file

### ISSUE THREAD

**Issue by thekomer** [flackbash/AudioAnchor#23]
Hey again!

As I've said, there is another issue.

Reproduce: Open app -> click on a book (its a folder) -> long press on a file -> app crashes with a popup "audioAnchor has stopped" and only option "open app again".

I know, I shouldn't long press files because that option is not implemented... never the less, it shouldn't crash the app. I think :)

Maybe it's only my device and my file...

When I'm on the subject,  you could maybe also implement option "send bug report" so ppl can send you logs and device info with one click. I've seen that option with other apps. When app crashes (just as your did) there are two options "open app again" and "send report". That's useful.

My device is: Sony XZ1 compact. Sony rom. 
I didnt modify device in any way. Androidd 8.0.
AudioAnchor: v1.9

That's all for now. I hope it helps. C ya!

**Comment by flackbash** [comment]
Ha! Indeed... Thanks for reporting this. And you are right, the app really shouldn't crash because you long click a file ;)
I found the problem and fixed it.

And I'll tell you a secret (which I should probably document properly at some point): Long clicking an item is implemented, but an action happens only if you have the setting _keep progress of deleted files in database_ enabled and the file does not exist anymore. In that case, a trash can icon is shown next to the item and when you long click the item you have the option to delete it from the database.

Sending a bug report is an idea worth thinking about. I'll do some research when I get the time.

**Comment by monreal** [comment]
Is this supposed to be fixed in the latest version published on f-droid? I still get the crash.

**Comment by flackbash** [comment]
No, the latest release on F-droid does not contain this fix yet.
