### ISSUE TITLE
Support Sub-directories

### ISSUE THREAD

**Issue by telematoxx** [flackbash/AudioAnchor#32]
I installed Version 2.0 and chose a directory with the file folders of two different Podcast fetcher apps. One app stores all files in one folder, the other APP uses subdirs for each subscription. The episodes of latter do not show up in AudioAnchor.

**Comment by flackbash** [comment]
Hm yes... unfortunately this will require quite a few changes. I hope to implement a solution for this eventually but it might take a while.

**Comment by flackbash** [comment]
This functionality is now implemented in the following way:

You can add multiple directories to your library instead of selecting a single parent directory. You can add directories in two different ways:
1) add a directory that contains audio files
2) add a directory that contains subdirectories which contain audio files

Adding directories can be nested although I would not recommend it.
So in your use case you have two options:

A) **[preferred]** add folder of the podcast fetcher that stores all files in one folder by selecting the option *Add directory that contains audio files*. Add the folder of the other podcast fetcher by selecting the option *Add directory that contains subdirectories which contain audio files*
B) alternatively you can keep the parent folder which you have currently selected and additionally add the folder of the podcast fetcher that uses subdirectories for each subscription using the option *Add directory that contains subdirectories which contain audio files*. This will however result in the latter podcast fetcher directory showing up as an empty directory as well (because your original parent directory was added using option 1)).

**Comment by hoxu** [comment]
Sweet! Can't wait to test this with the next release :tada:
