### ISSUE TITLE
AudioAnchor forgets current playback position

### ISSUE THREAD

**Issue by Self-Perfection** [flackbash/AudioAnchor#34]
I expect AudioAnchor to remember position at which I left playback of each file.

Actually after resuming playback I often find AudioAnchor playing from not the last position at which this file was paused, but penultimate pause position or even just the start of the file.

The last time this happened I noticed that in list of files current position was still displayed properly as 20:20 - where I actually paused the file, though it was playing from the start, but once I pressed "pause" it resetted to the actual current position, ~00:10. I'm not sure of this observation.

**Comment by flackbash** [comment]
Yes, I have made similar observations. I suspect that this issue and the headset issue #29 might be connected. I think the os might be deactivating or shutting off certain components (e.g. the MediaSession) after a while. It is difficult to debug since these issues do not occur during debugging. But I'm currently working on this and hope to find a solution soon. Thanks for reporting this anyway!
