### ISSUE TITLE
Support for audio files without folder

### ISSUE THREAD

**Issue by Russe** [flackbash/AudioAnchor#38]
Currently the player recognizes audio books only when the files are in a subfolder of parent directory.
As most of my audio books are single files, it's quiet boring to create for each file an own subfolder. It would be very nice when the player has support for single files parent directory.
Or is this already possible and I do not use it in the right way?

**Comment by flackbash** [comment]
As a simple hack for now you could just put them all in a single sub-directory of your parent directory. It just means one click more when you open the app (and does not look as pretty I admit). Right now, everything that touches the directory structure is a bit more complicated to implement, but I'll consider it for future improvements.

**Comment by Russe** [comment]
Thanks for your feedback.
Now I created some folders like categories for my single file audio books. Not so nice like you said (as well in this way it's not possible to have different thumbnails for each audio book), but less work than one folder for each single file.

**Comment by c33s** [comment]
would be good to have some info about this, i installed the app, selected a folder (where one mp3 file resides) and the app only shows me that there is no audio book found. until impementing the support of files without folders a help/info text would be nice like "no audio books found, if you put the audio book into directory you selected, move it into a subdirectory below the choosen directory" (or something like that)

thanks for this awesome and simple to use audio book player <3

**Comment by flackbash** [comment]
Yeah good point, I'll add something like that.

**Comment by r57zone** [comment]
It would be great to see this feature. Can create a category of "No category" or "General" for them.

**Comment by flackbash** [comment]
This functionality is now implemented in the following way:

You can add multiple directories to your library instead of selecting a single parent directory. You can add directories in two different ways:

1) add a directory that contains audio files (let's call it option "sub dir")
2) add a directory that contains subdirectories which contain audio files (aka option "parent dir")

Adding directories can be nested and although I would try not to if possible, this can be used in your case to achieve the following behavior:
Your original parent directory is automatically added using option *parent dir*. 
If this parent directory also contains audio files which you want to have listed, you can now simply add this parent directory again using option *sub dir*. This will result in your parent directory showing up in the list of subfolders containing the subfolder-less audio files.

**Comment by flackbash** [comment]
Closing this for now, since it is somehow covered through above mentioned functionality.
