### ISSUE TITLE
Can't delete tracks from filesystem unless export database first

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#68]
Hi. I long-pressed on a track, chose Delete from the menu (not "Delete from database"), pressed OK on the "are you sure" dialogue, but got the toast "0 track(s) deleted."

**Comment by flackbash** [comment]
Does that happen only for one specific file/only for files within a specific folder?
If so, is there anything out of the ordinary with that file or the folder that contains it?
Does it for example contain unusual characters (should not matter, but well..)?
You've probably checked that it still exists in the file system.

Any details will help me fix this, since I can't reproduce the bug on my system.

**Comment by JohnVeness** [comment]
Thanks for the reply. I've done a bit more digging. It was happening on any file in any folder, with no unusual characters.

I have worked something out. If I export the database, I can then delete tracks OK! It's as if exporting (i.e. writing to the storage) is triggering something which allows the app to delete..?

I have verified this by wiping the app's storage and trying again. It definitely can't delete tracks on my device until I export the database.

Very strange! Hope this gives you enough info to fix it.

**Comment by flackbash** [comment]
That definitely helps, thanks for investigating. I'll try to have a look at it soon.

**Comment by flackbash** [comment]
I implemented something that I think should fix your problem. I'm not entirely sure though, since I can't reproduce the bug on my system. 
Do you have AndroidStudio or Eclipse installed such that you can test the new code on your phone?
I could also send you a test apk if you like.
Otherwise it'll be in the next release.

**Comment by JohnVeness** [comment]
Thanks. I don't have Android Studio or Eclipse, but I'm happy to test an APK :)

**Comment by flackbash** [comment]
Great :) you can send an email to my email address [here](https://ad.informatik.uni-freiburg.de/staff/prange), then I'll send you an apk.

**Comment by flackbash** [comment]
Fixed. Thanks for your help :)
