### ISSUE TITLE
Track titles are shown as the filename rather than the title from the metadata

### ISSUE THREAD

**Issue by vnord** [flackbash/AudioAnchor#7]
Edit: accidentally pasted the wrong code. Title should still be self-explanatory though.

**Comment by jubalh** [comment]
Actually this is by purpse. And I like it like this. If this is going to be changed I hope we could have a setting to so we can choose.

**Comment by vnord** [comment]
I understand. A setting to choose would be great, though! I really like that the tracks are sorted by filename, but I happen to have some pretty wonky file names which don't look too good, and they make it hard to find what I'm looking for.

**Comment by jubalh** [comment]
> but I happen to have some pretty wonky file names which don't look too good

Yes totally understandable. I personally use some bash scripting to have nice filenames. But I totally get that for some people it's not an option, and for this reason your feature request makes sense.

**Comment by vnord** [comment]
> > but I happen to have some pretty wonky file names which don't look too good
> 
> Yes totally understandable. I personally use some bash scripting to have nice filenames. But I totally get that for some people it's not an option, and for this reason your feature request makes sense.

I already used some bash scripting to e.g. add the date from the metadata as a prefix to the file names, but it just looks a bit messy when listing them in an app, and I don't need all the info that the filename provides when just listening to podcasts/audiobooks.

I could look into implementing it -- I used MediaMetaDataReceiver to find the title and got that to work for the PlayActivity and the notification, but I had a bit of trouble getting the listing in the album view to change the titles correctly. Do you have any suggestions for the "right" way of implementing it?

**Comment by jubalh** [comment]
Sorry I have no idea about Android development whatsoever :-)
We will have to wait for the awesome @flackbash to reply.

**Comment by flackbash** [comment]
I think adding an option in the settings is a good idea. It might get a little bit more complicated to implement since it might make sense to make alterations to the database. I haven't had a closer look at it yet, but I will soon.

**Comment by flackbash** [comment]
If you still would like to implement this - I would leave the database as is for now. Then all you have to do for the AlbumActivity to display the correct title is this:

The views of the AlbumActivity list are set in the AudioFileCursorAdapter class.
As far as I understand the MediaMetadataRetriever you would have to extract the path of the audio file from the cursor in bindView(), similarly as I [extract the audio title](https://github.com/flackbash/AudioAnchor/blob/7c1895f6df5df1b5c3a1b9e89791b3255300ef5f/app/src/main/java/com/prangesoftwaresolutions/audioanchor/AudioFileCursorAdapter.java#L41)  and set it as data source.
Then extract the necessary information (you seem to have already managed that) and set the titleTV to the title retrieved from the meta data.
You can use sharedPreferences as you did in your previous pull request to add an option to the settings to retrieve the title from the metadata.

Let me know if you still want to do it, otherwise I will happily implement it :)

**Comment by vnord** [comment]
Sorry, I forgot to write a timely reply! I'd be more than happy to implement it wheny vacation starts in about 10 days. Thanks for the leads!

**Comment by flackbash** [comment]
@vnord Do you still want to implement this? I will try to publish a new release within the next week and would like to have this feature in it. So unless I hear from you before, I'll implement this within the next few days.

**Comment by vnord** [comment]
@flackbash I completely forgot about this. My apologies. I don't think I'll have time to look at this now, so please go ahead and implement it :-)
