### ISSUE TITLE
App crashes if playback speed goes above certain level

### ISSUE THREAD

**Issue by dspacejs** [flackbash/AudioAnchor#76]
The app crashes (without an error log) if I set the playback speed to 2.5. But if I set it to 2.4 or lower, it works fine.

**Comment by flackbash** [comment]
I can't reproduce this on my device.
- Are you on AudioAnchor version 2.2?
- Which Android version are you on?
- And probably most importantly: does that happen for all files or just for some of them? Are these mp3 files? Could you give me a link to a file where that happens?

Thanks for reporting this.

**Comment by dspacejs** [comment]
@flackbash sorry for the lack of info, I forgot to provide it. Here you go:

AudioAnchor version: 2.2
Android version: 10 (on Graphene OS)

The files are .mp3 files. The audiobook is The Mind Illuminated by Culadasa. Not sure if I can legally give you a link? 

I just tried with another audiobook and it works now. In fact it even works with the same file I tried earlier. I don't know what's happened since then, I don't think any updates have been applied. Therefore I'm not sure how you can reproduce the problem.

**Comment by dspacejs** [comment]
@flackbash just happened again, this time on a different speed (anything above 2.5). It was a different audiobook as well. I'm not sure what's causing this. Is there an error log I can view? I can't find any bug reporting in the app. Thanks.

**Comment by flackbash** [comment]
Ok, weird. And difficult to debug since I can't reproduce it and you can't seem to reproduce it reliably, either.
Unless you have Android Studio or Eclipse installed for debugging, it's not possible to view an error log at the moment.

Some more information might help to narrow it down:
- With this new file you can reproduce the described behavior every time?
- Does this happen only if you change the speed while the file is playing? Or only if you first select a file, then change the speed and then start the playback? Or in either scenario?
- If playback is paused, and you then change the speed to above 2.5, does the app crash directly or only once you click play?
- Do you have other media players installed with which you can change the playback speed? If so, does increasing the playback speed there to something about 2.5 work as expected?

I would assume that this is an Android Media Player problem or maybe something related to the phone or OS you are using but I can't be sure.

**Comment by dspacejs** [comment]
>  Unless you have Android Studio or Eclipse installed for debugging, it's not possible to view an error log at the moment.

I don't have these installed or know how to use them, unfortunately. I have enabled adb for my phone though because I installed Graphene OS, so perhaps this might be straightforward to do?

> With this new file you can reproduce the described behavior every time?

Nope. 

> Does this happen only if you change the speed while the file is playing? Or only if you first select a file, then change the speed and then start the playback? Or in either scenario?

Not sure. Next time it happens I need to test this.

> If playback is paused, and you then change the speed to above 2.5, does the app crash directly or only once you click play?

Same as above.

> Do you have other media players installed with which you can change the playback speed? If so, does increasing the playback speed there to something about 2.5 work as expected?

Yeah, it works fine.

> Can you check the audio file properties, like Codec, bit rate, whether it's variable bit rate (VBR) or constant bit rate (CBR).

Not sure how to check the VBR or CBR? This is the info in my file browser:

* Codec: MPEG-1 Layer 3 (MP3)
* Channels: Stereo
* Sample rate: 22050 Hz
* Bit rate: N/A

**Comment by dspacejs** [comment]
@flackbash good news, figured out how to get a log using `adb logcat`. Here's a crash log for you:

[crash.log](https://github.com/flackbash/AudioAnchor/files/5358610/crash.log)

**Comment by flackbash** [comment]
Great, thank you! I'll have a look at it.

**Comment by GenosseFlosse** [comment]
I got the same issue:
POCOPHONE f1 Android 10
![Screenshot_2020-10-14-00-11-32-471_com.miui.bugreport.png](https://user-images.githubusercontent.com/59205524/95921681-0722e800-0db2-11eb-82a1-de951fa59774.png)
App version 2.2
Crashes when setting playback speed to more than 2.
Sry for just providing the Photo of the log, but xiaomi won't let me copy it...
Otherwise great app, thank you!

**Comment by flackbash** [comment]
I haven't found a way to get the native Android MediaPlayer to play the file at the selected speed. My guess is, that the problem is related to the bit rate of the audio file.

But I implemented error handling, such that the user will now be informed if they select a playback speed that is outside the valid range for that file. So the app doesn't crash anymore and you just have to select a different speed value.
This will be in the next release. If the bug persists, feel free to reopen this issue.

Thanks @dspacejs and @GenosseFlosse for your help.

**Comment by GenosseFlosse** [comment]
@flackbash Your Bugfix solved the issue for me. The same mp3 files now work flawlessly, thank you!

**Comment by flackbash** [comment]
Great :)

**Comment by dspacejs** [comment]
@flackbash so I can't go up to 3x speed on some files? This is strange because I can do this with other apps

**Comment by flackbash** [comment]
Exactly. I would assume that the other apps don't use the native Android MediaPlayer. However, getting rid of the MediaPlayer would most likely involve heavy changes, for which I don't have the capacity right now.

You could try the following (the result would be interesting for me, too):
in case you are using Linux, install SoundConverter and use it to convert the file to a constant bitrate of 128kbps (Preferences -> Bitrate mode: Constant, Quality: Normal) and check if the problem persists.
Similar tools exist for Windows as well.
